name: Test schedule

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "37 * * * *"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Mostrar fecha
        run: |
          echo "Evento: ${{ github.event_name }}"
          date -u
