name: Test schedule

on:
  workflow_dispatch:
  schedule:
    - cron: "0,5,10,15,20,25,30,35,40,45,50,55 * * * *"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Mostrar fecha
        run: |
          echo "Evento: ${{ github.event_name }}"
          date -u
